language: node_js
node_js:
  - "node"

cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
    - "node_modules"

script: yarn build

before_deploy: 
  - npm install --global now

env:
  - PROJECT_TYPE=client
  - PROJECT_TYPE=server

deploy:
  provider: script
  script: bash ./scripts/deploy_$PROJECT_TYPE.sh
  skip_cleanup: true
  on:
    master: true

