language: node_js
node_js:
  - "node"

cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
    - "node_modules"

script: yarn build

before_deploy: 
  - npm install --global now
deploy:
  - provider: script
    script: cd client && now --public --token $NOW_TOKEN && now alias --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
