language: node_js
node_js:
  - "node"

cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
    - "node_modules"

script: yarn build

before_deploy: 
  - npm install --global now
  - now rm f1setup-api --safe --yes
  - now rm f1setup --safe --yes

env:
  - PROJECT_TYPE=client
  - PROJECT_TYPE=server

deploy:
  provider: script
  script: cd $PROJECT_TYPE && now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
  skip_cleanup: true
  on:
    master: true

