language: node_js
node_js:
  - "node"

env:
  - PROJECT_DIR=server
  - PROJECT_DIR=client

cache:
  directories:
    - "$PROJECT_DIR/node_modules"

before_script: 
  - cd $PROJECT_DIR

compile: yarn
test: yarn test
